name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Pelican and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown

    - name: Build the site
      run: |
        pelican content -o output -s pelicanconf.py

    - name: Deploy to GitHub Pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true

